# Generated by Django 3.1.5 on 2021-09-04 17:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210904_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=tinymce.models.HTMLField(blank='True', null='True'),
        ),
    ]
